apiVersion: v1
kind: PersistentVolume
metadata:
  name: mealie-data-pv
  namespace: mealie
spec:
  capacity:
    storage: 500Mi  # A kívánt tárolókapacitás
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path  # Használja a local-path provisionert
  hostPath:
    path: /tmp/mealie-data  # Helyi tároló elérési útja a node-on

