apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: maelie-data
  namespace: mealie
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: local-path
